# Generated by Django 5.1.7 on 2025-03-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=50)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Phone Number', max_length=15)),
                ('subject', models.CharField(help_text='Subject', max_length=250)),
                ('message', models.TextField(help_text='Message')),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_result', models.TextField()),
                ('description', models.TextField()),
                ('diet', models.TextField()),
                ('workout', models.TextField()),
                ('medication', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user_model')),
            ],
        ),
    ]
